name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Change gateway
      run: cd api-gateway
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag evaldas483:$(date +%s)
